name: 'Setup Railway CLI'
description: 'Set up Railway CLI for usage in GitHub Actions'
branding:
  icon: arrow-down
  color: purple

inputs:
  npm-mode:
    required: false
    description: Install Railway CLI with npmjs
    default: 'false'
  repo-url:
    description: Git URL of custom Railway CLI source. Use the canocial repo to test new features before they land on Deploy Fridays.
    default: ''
    required: false
  repo-branch:
    required: false
    description: "Git branch of custom Railway CLI source. When building from fhe official repo's source, use master branch."
    default: ''

runs:
  using: node12
  main: dist/index.js
