#!/bin/bash

CLONE_DIR=$1
BRANCH=$3
REPO=$2

# Clone repo first
if [[ $BRANCH != "" ]]; then
  git clone -b "$BRANCH" "$REPO" "$CLONE_DIR"
else
  git clone "$REPO" "$CLONE_DIR"
fi

# Install deps
cd "$CLONE_DIR" || echo "Clone directory not found" && exit 2
go get --verbose -t -d ./...

# The build and move to /usr/bin/local
VERBOSE=1 go build -o bin/railway
# Temporarily move to /usr/bin
sudo mv $CLONE_DIR/bin/railway /usr/bin/railway

# ensure it's executable
sudo chmod +x /usr/bin/railway
