#!/bin/bash

mkdir $GITHUB_WORKSPACE/.npm-global
NPM_CONFIG_PREFIX=$GITHUB_WORKSPACE/.npm-global npm install -g @railway/cli
sudo ln -s $GITHUB_WORKSPACE/.npm-global/bin/railway /usr/lib/node_modules/bin/railway
